# Generated by Django 4.1.2 on 2022-10-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ranking_fifa', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('fase', models.CharField(choices=[('Grupos', 'Grupos'), ('Octavos', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semis', 'Semis'), ('3er y 4to', '3er y 4to'), ('Final', 'Final')], default='Grupos', max_length=20)),
                ('cntequipos', models.IntegerField(default=32)),
                ('equipos', models.ManyToManyField(through='Torneos.Clasificado', to='Torneos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('score_local', models.IntegerField(default=0)),
                ('score_visitante', models.IntegerField(default=0)),
                ('resultado', models.CharField(choices=[('E', 'Empate'), ('L', 'Local'), ('V', 'Visitante')], default='E', max_length=1)),
                ('local', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partido_local', to='Torneos.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneos.torneo')),
                ('visitante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partido_visitante', to='Torneos.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='clasificado',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneos.equipo'),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneos.torneo'),
        ),
    ]
