# Generated by Django 4.1.2 on 2022-10-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificado',
            options={'ordering': ['torneo', 'grupo']},
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fase',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Grupos', 'Grupos'), ('Octavos', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semis', 'Semis'), ('3er y 4to', '3er y 4to'), ('Final', 'Final')], default='Grupos', max_length=20),
        ),
    ]
