# Generated by Django 4.1.2 on 2022-10-21 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0002_alter_clasificado_options_alter_torneo_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='local',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partido_local', to='Torneos.clasificado'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='visitante',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partido_visitante', to='Torneos.clasificado'),
        ),
    ]
