# Generated by Django 4.1.2 on 2022-10-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0004_alter_partido_local_alter_partido_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='fase',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Grupos', 'Grupos'), ('Octavos', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semis', 'Semis'), ('3er y 4to', '3er y 4to'), ('Final', 'Final')], default='Pendiente', max_length=20),
        ),
    ]
