# Generated by Django 4.1.2 on 2022-10-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0009_partido_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='grupos',
            field=models.IntegerField(default=8),
        ),
    ]
