# Generated by Django 4.1.2 on 2022-10-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0011_torneo_grupos_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='clasificanXgrupo',
            field=models.IntegerField(default=2),
        ),
    ]
