# Generated by Django 4.1.2 on 2022-10-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0013_alter_partido_local_alter_partido_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='codigo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='grupos_mod',
            field=models.CharField(choices=[('I', 'Ida'), ('IV', 'Ida y Vuelta')], default='I', max_length=2),
        ),
    ]
