# Generated by Django 4.1.2 on 2022-10-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0014_alter_partido_codigo_alter_torneo_grupos_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='bandera',
            field=models.ImageField(default="{% media 'default.png' %}", upload_to='equipos_foto'),
        ),
    ]
