# Generated by Django 4.1.2 on 2022-10-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0015_alter_equipo_bandera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='bandera',
            field=models.ImageField(default='default.png', upload_to='equipos_foto'),
        ),
    ]
