# Generated by Django 4.1.2 on 2022-10-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0020_grupo_alter_clasificado_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificado',
            name='grupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1),
        ),
    ]
