# Generated by Django 4.1.2 on 2022-10-31 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0021_alter_clasificado_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificado',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneos.grupo'),
        ),
    ]
