# Generated by Django 4.1.2 on 2022-11-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0022_alter_clasificado_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificado',
            name='empatados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='ganados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='goles_C',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='goles_D',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='goles_F',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='jugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='perdidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'Empate'), ('L', 'Local'), ('V', 'Visitante')], default='E', max_length=1),
        ),
    ]
