# Generated by Django 4.1.2 on 2022-11-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0024_alter_clasificado_options_partido_modif_ranking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificado',
            options={'ordering': ['grupo', '-puntos', '-goles_D']},
        ),
    ]
