# Generated by Django 4.1.2 on 2022-11-03 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Torneos', '0025_alter_clasificado_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('pts_ganador', models.IntegerField(default=0)),
                ('pts_resultado', models.IntegerField(default=0)),
                ('pts_pasafase', models.IntegerField(default=0)),
                ('pts_terycuar', models.IntegerField(default=0)),
                ('pts_segundo', models.IntegerField(default=0)),
                ('pts_primero', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['usuario', '-puntos'],
            },
        ),
        migrations.AddField(
            model_name='torneo',
            name='torneoPadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Torneo_padre', to='Torneos.torneo'),
        ),
        migrations.CreateModel(
            name='Penca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('buy_in', models.FloatField(default=0)),
                ('pts_ganador', models.IntegerField(default=3)),
                ('pts_resultado', models.IntegerField(default=2)),
                ('pts_pasafase', models.IntegerField(default=6)),
                ('pts_terycuar', models.IntegerField(default=6)),
                ('pts_segundo', models.IntegerField(default=10)),
                ('pts_primero', models.IntegerField(default=20)),
                ('participantes', models.ManyToManyField(through='Torneos.Participante', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneos.torneo')),
            ],
            options={
                'ordering': ['fecha', 'nombre', 'torneo'],
            },
        ),
        migrations.AddField(
            model_name='participante',
            name='penca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneos.penca'),
        ),
        migrations.AddField(
            model_name='participante',
            name='torneo_hijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneos.torneo'),
        ),
        migrations.AddField(
            model_name='participante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
