# Generated by Django 4.1.2 on 2022-11-04 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0027_penca_administrador_alter_penca_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='torneo_hijo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Torneos.torneo'),
        ),
    ]
