# Generated by Django 4.1.2 on 2022-11-04 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0028_alter_participante_torneo_hijo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penca',
            name='participantes',
        ),
    ]
