# Generated by Django 4.1.2 on 2022-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0030_alter_partido_score_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='score_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='score_visitante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
