# Generated by Django 4.1.2 on 2022-11-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0031_alter_partido_score_local_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={'ordering': ['-puntos', 'usuario', '-pts_resultado']},
        ),
    ]
