# Generated by Django 4.1.2 on 2022-11-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0032_alter_participante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['torneo']},
        ),
    ]
