# Generated by Django 4.1.2 on 2022-11-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Torneos', '0033_alter_partido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['fecha', 'torneo']},
        ),
    ]
